variables:
  KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: ci-pipeline-maf

before_script:
  - npm install -g lerna

stages:
  - testpr
  - deploy

testpr:
  stage: testpr
  image: node:12.14.0
  tags:
    - cicd-runner-maf
  script:
    - echo "this is merge requests test"
  only:
    - merge_requests

deploy_prod:
  stage: deploy
  image: node:12.14.0
  tags:
    - cicd-runner-maf
  script:
    # - lerna publish from-package --yes
  only:
    - master
