image: node:12.16.2
cache:
  paths:
    - node_modules/
    - .yarn

variables:
  KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: ci-pipeline-maf

before_script:
  - npm install -g lerna

stages:
  - testpr
  - deploy

testpr:
  stage: testpr
  tags:
    - cicd-runner-maf
  script:
    - yarn test
  only:
    - merge_requests

deploy_prod:
  stage: deploy
  tags:
    - cicd-runner-maf
  script:
    # - lerna publish --registry https://nexus.exelator.net/repository/npm-internal/ --yes
  only:
    - master
